name: jewellery
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0

  dio: 5.1.1



  firebase_auth: ^4.9.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  get: ^4.6.5
  animated_text_kit: ^4.2.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.9.0
  image_picker: ^1.0.2
  fast_cached_network_image: ^1.2.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  photo_view: ^0.14.0
  share: ^2.0.4
  path_provider: ^2.1.1
  fluttertoast: ^8.2.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  url_launcher: ^6.1.14
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo6.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo6.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - assets/images/














 